/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ProdutoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Produto;

/**
 *
 * @author guilherme
 */
public class listarProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form listarProduto
     */
    public listarProduto() {
        initComponents();
        listarProdutoDono();
    }
    
    public void listarProdutoDono(){
        
        /*List<Categorias> lista = CategoriasDAO.getCategorias();
        DefaultTableModel model = new DefaultTableModel();
        String[] colunas = {"Código","Nome"};
        
        
        model.setColumnIdentifiers(colunas);
        
        for(Categorias cate : lista){
            Object[] linha = {cate.getId(),cate.getNome()};
            model.addRow(linha);
        }
        
        tableCategorias.setModel(model);*/
        
        List<Produto> lista = ProdutoDAO.getProduto();
        DefaultTableModel model = new DefaultTableModel();
        String[] colunas = {"Codigo","Nome","Tipo","Preco"};
        
        model.setColumnIdentifiers(colunas);
        
        for(Produto pro: lista){
            Object[] linha = {pro.getId(),pro.getNome(),pro.getTipo(),pro.getPreco()};
            model.addRow(linha);
        }
        
        txtTabela.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTabela = new javax.swing.JTable();
        btnDeletar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Listar Produto");

        txtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Tipo", "Preco"
            }
        ));
        jScrollPane1.setViewportView(txtTabela);

        btnDeletar.setText("deletar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletar)
                .addGap(0, 110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnDeletar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable txtTabela;
    // End of variables declaration//GEN-END:variables
}
