/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.PedidoDAO;
import dao.ProdpadDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.Pedido;
import model.Prodpad;
import model.Produto;


/**
 *
 * @author guilherme
 */
public class ListaPedido extends javax.swing.JInternalFrame {
    
    private List<Prodpad> listaPedidoSelecionado;
    //teste
    private List<Produto> listaProduto;

    /**
     * Creates new form ListaPedido
     */
    public ListaPedido() {
        initComponents();
        listaPedidoSelecionado = new ArrayList<>();
        //teste
       // listaProduto = new ArrayList<>();
        carregaPedido();
        
        
        
        
    }
    
    public void carregaPedido(){
        
        /* List<Produto> listaProduto = ProdutoDAO.getProduto();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        Produto fake = new Produto();
        fake.setNome("Selecione...");
        model.addElement( fake);
        for (Produto pro : listaProduto){
            model.addElement(pro);
        }
        cmbPedido.setModel(model);*/
        
        List<Pedido> listaPedido = PedidoDAO.getPedido();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        Pedido fake = new Pedido();
        fake.getId();
        fake.getData();
        model.addElement(fake);
        for(Pedido p: listaPedido){
            model.addElement(p);
        }
        
        jcMostraPedido.setModel(model);
        
        
        
        
    }
    
    public void carregarTabela(){
        
        /*
        DefaultTableModel model = new DefaultTableModel();
        String[] colunas = {"Codigo","Nome","Tipo","preco"};
        
        
        model.setColumnIdentifiers(colunas);
        
        for(Produto pro:produtosSelecionados){
            
            Object[] linha = { pro.getId(),pro.getNome(),pro.getTipo(),pro.getPreco()};
            model.addRow(linha);
             
                   

                
        
            
        }
        tableProdutosSelecionados.setModel( model );
        */
        
       /*
        //Tentativa
        DefaultTableModel model = new DefaultTableModel();
        String[] colunas = {"id","CodPedido","CodProduto","Produto"};
        
        model.setColumnIdentifiers(colunas);
        
        for(Prodpad pro: listaPedidoSelecionado){
            
            Object[] linha = {pro.getId(),pro.getCodPedido(),pro.getCodProduto(),};
            
        }
        tabelaListaP.setModel(model);*/
       
        DefaultTableModel model = new DefaultTableModel();
        String[] colunas = {"id","CodPedido","CodProduto","Produto"};
        
        model.setColumnIdentifiers(colunas);
        
        for(Prodpad pro: listaPedidoSelecionado){
            
            
            for(Produto pr: listaProduto){
            Object[] linha = {pro.getId(),pro.getCodPedido(),pro.getCodProduto(),pr.getNome()};
            model.addRow(linha);
            
            }
            
        }
        tabelaListaP.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMostraPedido = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListaP = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();

        setTitle("Listar Pedidos");

        tabelaListaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaListaP);

        btnAdicionar.setText("Pegar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jcMostraPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcMostraPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        /*Pedido ped = new Pedido();
        
        Calendar hoje = Calendar.getInstance();
        String data = hoje.get(Calendar.YEAR) + "-" + (hoje.get(Calendar.MONTH) +1 ) + "-" + hoje.get(Calendar.DAY_OF_MONTH)   ;
        ped.setData(data);
        
        int idPedido = PedidoDAO.inserir(ped);
        
        for(Produto pro: produtosSelecionados ){
            Prodpad prodpad = new Prodpad();
            prodpad.setCodPedido(idPedido);
            prodpad.setCodProduto(pro.getId());
            prodpad.setPreco(pro.getPreco());
            prodpad.setQtd(1);
            ProdpadDAO.inserir(prodpad);
        }*/
        
        for(Prodpad pro: listaPedidoSelecionado){
            Prodpad prodpad = new Prodpad();
            Produto pr = new Produto();
            prodpad.getId();
            prodpad.getCodPedido();
            prodpad.getCodProduto();
            pr.getNome();
            ProdpadDAO.inserir(prodpad);
            
            
        }
        
        
    }//GEN-LAST:event_btnAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcMostraPedido;
    private javax.swing.JTable tabelaListaP;
    // End of variables declaration//GEN-END:variables
}
